/*
1. You are given a number N, which represents the count of buttons pressed on a mobile numeric keypad.
2. You can only press buttons that are up, left, right, down to the current button and the current button also.
3. You can not press bottom row corner buttons(* and #).

4. You have to find the count of different numbers that can be generated by pressing N number of buttons.
*/

import java.io.*;
import java.util.*;

public class Main {

	public static int solution(int n) {
		//use dp
		
		int[][] dp = new int[n + 1][10];
		//row -> no of press done
		//col -> key
		
		//(i, j)th box stores count of numbers which end with jth key after i no of presses
		
	    //array of arraylist to store from which key we can go to which key
	    ArrayList<Integer>[] allowed = new ArrayList[10];//for 10 keys
	    
	    allowed[0] = new ArrayList<>(Arrays.asList(0, 8));
	    allowed[1] = new ArrayList<>(Arrays.asList(1, 2, 4));
	    allowed[2] = new ArrayList<>(Arrays.asList(1, 2, 3, 5));
	    allowed[3] = new ArrayList<>(Arrays.asList(2, 3, 6));
	    allowed[4] = new ArrayList<>(Arrays.asList(1, 4, 5, 7));
	    allowed[5] = new ArrayList<>(Arrays.asList(2, 4, 5, 6, 8));
	    allowed[6] = new ArrayList<>(Arrays.asList(3, 5, 6, 9));
	    allowed[7] = new ArrayList<>(Arrays.asList(4, 7, 8));
	    allowed[8] = new ArrayList<>(Arrays.asList(0, 5, 7, 8, 9));
	    allowed[9] = new ArrayList<>(Arrays.asList(6, 8, 9));
	    
		
		for(int i = 1; i <= n; i++){
		    for(int j = 0; j < 10; j++){
		        if(i == 1){
		            //if only 1 press is done, 1 number is possible for any key
		            dp[i][j] = 1;
		        }else{
		            //depends on number upto i - 1 press
		            //add all values of keys from which we can come to jth key
		            
		            //prev are the keys from which we can come to j
		            for(int prev : allowed[j]){
		                dp[i][j] += dp[i - 1][prev];
		            }
		        }
		    }
		}
		
		int sum = 0;
		for(int j = 0; j < 10 ; j++){
		    sum += dp[n][j];
		}

		return sum;
	}
	public static void main(String[] args) {
		Scanner scn = new Scanner(System.in);
		System.out.println(solution(scn.nextInt()));
	}

}
